#!/usr/bin/env python3
"""
arXiv + Semantic Scholar hybrid paper search script.
Used by the paperadar skill to find highly influential and high-quality
papers from the past week and past year.
"""

import xml.etree.ElementTree as ET
import json
import re
import os
import sys
import time
import logging
from datetime import datetime, timedelta
from typing import List, Dict, Set, Optional, Tuple
from pathlib import Path
import urllib.request
import urllib.parse

logger = logging.getLogger(__name__)


def title_to_note_filename(title: str) -> str:
    """Convert a paper title to an Obsidian note filename (consistent with generate_note.py).

    Applies the exact same rules as paper-analyze/scripts/generate_note.py so
    that wikilinks generated by paperadar correctly resolve to files created
    by paper-analyze.
    """
    filename = re.sub(r'[ /\\:*?"<>|]+', '_', title).strip('_. ')
    return filename

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False
    logger.warning("requests library not found, using urllib for Semantic Scholar API")

# Bio sources: optional modules in the same scripts/ directory
# BIO_SOURCES_STATUS is a free-form string that the orchestrator (SKILL.md
# Step 2 guard) reads from the output JSON's `bio_status` field. Values:
#   "ok"                — both PubMed and bioRxiv imports + calls succeeded
#   "import_failed: …"  — script-level ImportError (Bio package missing etc.)
#   "api_error: …"      — runtime HTTP error from PubMed eutils or bioRxiv
#                         (set by the caller code path that wraps the search)
# Per the project's *"sanity checks must fail loud"* rule, a non-"ok" value
# triggers a stderr WARN line in the SKILL.md guard so the user knows the
# top-N may be incomplete.
BIO_SOURCES_STATUS = "ok"
try:
    _scripts_dir = os.path.dirname(os.path.abspath(__file__))
    if _scripts_dir not in sys.path:
        sys.path.insert(0, _scripts_dir)
    from search_pubmed import search_pubmed
    from search_biorxiv import search_biorxiv
    HAS_BIO_SOURCES = True
except ImportError as e:
    HAS_BIO_SOURCES = False
    BIO_SOURCES_STATUS = f"import_failed: {e}"
    logger.warning("Bio source modules (search_pubmed, search_biorxiv) "
                   "not found — skipping (%s)", e)

# Optional cross-disciplinary sources beyond arXiv + Semantic Scholar. Each is
# a self-contained module imported best-effort (a missing file just drops that
# source). key_env=None means keyless — runs by default; otherwise the source
# runs under "auto" only when that env var holds a key. Adding a source is one
# _register_extra_source() line plus the module.
_EXTRA_SOURCES = []  # list of {name, fn, cfg_key, key_env}


def _register_extra_source(name, module_name, fn_name, cfg_key, key_env, default="auto"):
    try:
        mod = __import__(module_name)
        _EXTRA_SOURCES.append({
            "name": name, "fn": getattr(mod, fn_name),
            "cfg_key": cfg_key, "key_env": key_env, "default": default,
        })
    except ImportError as e:
        logger.warning("Optional source %s unavailable — skipping (%s)", name, e)


_register_extra_source("OpenAlex", "search_openalex", "search_openalex", "openalex", "OPENALEX_API_KEY")
_register_extra_source("Crossref", "search_crossref", "search_crossref", "crossref", None)
# CORE is opt-in (default off). The QC found CORE returns recently-*indexed* but not
# recently-*published* works, so it contributed nothing to a weekly top-N while adding
# fetch latency. Enable explicitly with `core: { enabled: true }`.
_register_extra_source("CORE", "search_core", "search_core", "core", "CORE_API_KEY", default="false")

# ---------------------------------------------------------------------------
# API configuration
# ---------------------------------------------------------------------------
ARXIV_NS = {
    'atom': 'http://www.w3.org/2005/Atom',
    'arxiv': 'http://arxiv.org/schemas/atom'
}

SEMANTIC_SCHOLAR_API_URL = "https://api.semanticscholar.org/graph/v1/paper/search"
SEMANTIC_SCHOLAR_FIELDS = "title,abstract,publicationDate,citationCount,influentialCitationCount,url,authors,authors.name,authors.affiliations,externalIds,venue,publicationVenue"


def _normalize_authors(authors) -> list:
    """Flatten a mixed-type author list into a plain list[str].

    arXiv returns `["Name1", "Name2"]` (strings); Semantic Scholar
    returns `[{"name": "Name1", "affiliations": [...]}, ...]` (dicts).
    Downstream consumers (the weekly note formatter, save_to_zotero,
    `jq` queries against arxiv_filtered.json) all expect strings.

    Normalising at the source — here in search_arxiv — means
    `arxiv_filtered.json` always has `authors: ["...", ...]`, which is
    `jq`-friendly and removes the band-aid case-split that used to live
    in `save_to_zotero._paper_to_zotero_item`.

    Empty / None inputs return []. Affiliation info is dropped during
    flattening — it lives separately under `paper["affiliations"]`.
    """
    out = []
    for a in authors or []:
        if isinstance(a, dict):
            name = (a.get("name") or "").strip()
        elif isinstance(a, str):
            name = a.strip()
        else:
            name = str(a).strip()
        if name:
            out.append(name)
    return out

# Default category-to-keyword mapping (used when no user-defined keywords are in the config).
# The primary set covers q-bio.* subcategories — this skill targets biology/biochemistry
# researchers by default. cs.* subcategory mappings are kept so users who repurpose
# the skill for ML papers can still supply cs.* categories in their YAML.
ARXIV_CATEGORY_KEYWORDS = {
    # Biology / quantitative biology — primary
    "q-bio.GN": "genomics",
    "q-bio.QM": "quantitative methods",
    "q-bio.CB": "cell behavior",
    "q-bio.MN": "molecular networks",
    "q-bio.BM": "biomolecules",
    "q-bio.PE": "populations evolution",
    "q-bio.SC": "subcellular processes",
    "q-bio.NC": "neurons cognition",
    "q-bio.TO": "tissues organs",
    "q-bio.OT": "biology other",
    # Computer science — kept for users who repurpose the skill for ML papers
    "cs.AI": "artificial intelligence",
    "cs.LG": "machine learning",
    "cs.CL": "computational linguistics natural language processing",
    "cs.CV": "computer vision",
    "cs.MM": "multimedia",
    "cs.MA": "multi-agent systems",
    "cs.RO": "robotics",
}

# ---------------------------------------------------------------------------
# Scoring constants — scoring constants + functions live in `scripts/_scoring.py`
# since 2026-05 (DEFERRED.md #5). Re-imported here so existing call sites
# and test imports (`from search_arxiv import calculate_recency_score`)
# keep working without touching test code.
# ---------------------------------------------------------------------------
from _scoring import (  # noqa: E402
    SCORE_MAX,
    RELEVANCE_TITLE_KEYWORD_BOOST,
    RELEVANCE_SUMMARY_KEYWORD_BOOST,
    RELEVANCE_CATEGORY_MATCH_BOOST,
    RECENCY_THRESHOLDS,
    RECENCY_DEFAULT,
    WEIGHTS_NORMAL,
    WEIGHTS_HOT,
    calculate_relevance_score,
    calculate_recency_score,
    calculate_quality_score,
    calculate_recommendation_score,
    _resolve_reference_now,
)

# Minimum keyword-only relevance (excluding arXiv category match contribution).
# A paper must match at least 1 keyword in the title (0.5) OR 2 keywords in the
# abstract (0.6) to pass — prevents broad-category + 1 incidental word false positives.
# Stays here (not in _scoring.py) because only `filter_and_score_papers`
# uses it — it's an orchestrator-level filter threshold, not a scoring
# primitive.
MIN_KEYWORD_ONLY_RELEVANCE = RELEVANCE_TITLE_KEYWORD_BOOST  # 0.5

# Pattern to detect arXiv category strings in matched_keywords (e.g. 'q-bio.GN', 'cs.AI')
ARXIV_CATEGORY_PATTERN = re.compile(r'^[a-z][a-z\-]*\.[A-Z]{1,3}$')

# Popularity: influential citation count normalised to 0–SCORE_MAX.
# A paper reaching this citation count receives a full popularity score. Used by filter_and_score_papers,
# not by the scoring primitives in _scoring.py.
POPULARITY_INFLUENTIAL_CITATION_FULL_SCORE = 100

# Semantic Scholar rate-limit back-off wait time (seconds)
S2_RATE_LIMIT_WAIT = 30
S2_CATEGORY_REQUEST_INTERVAL = 3

# Semantic Scholar API key (optional; read from the config file)
S2_API_KEY = None


def load_research_config(config_path: str) -> Dict:
    """
    Load the research-interests configuration from a YAML file.

    Args:
        config_path: Path to the config file.

    Returns:
        Research configuration dictionary.
    """
    import yaml
    
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        # Read the Semantic Scholar API key if configured
        global S2_API_KEY
        S2_API_KEY = config.get('semantic_scholar_api_key')
        return config
    except Exception as e:
        logger.error("Error loading config: %s", e)
        # Fallback config — generic biology-focused example domains. Users with
        # their own YAML never hit this branch; it exists so the skill does
        # *something* sensible when run without configuration. These are
        # illustrative areas, not anyone's specific research — see
        # config.example.yaml and replace them with your own topics.
        # Note: "3D" is excluded in some upstream AI-paper templates because
        # it conflicts with computer-vision papers, but in biology "3D" is a
        # meaningful term (3D genome, 3D chromatin) so it is NOT excluded.
        return {
            "research_domains": {
                "Genomics & Genome Biology": {
                    "keywords": [
                        "genome", "genomics", "genome assembly",
                        "structural variant", "variant calling",
                        "comparative genomics", "population genetics", "GWAS",
                    ],
                    "arxiv_categories": ["q-bio.GN", "q-bio.PE"],
                    "priority": 4,
                },
                "Gene Regulation & Epigenetics": {
                    "keywords": [
                        "transcription factor", "enhancer", "promoter",
                        "chromatin accessibility", "DNA methylation",
                        "histone modification", "ATAC-seq", "ChIP-seq",
                        "gene regulation",
                    ],
                    "arxiv_categories": ["q-bio.GN", "q-bio.MN"],
                    "priority": 4,
                },
                "Single-cell Biology": {
                    "keywords": [
                        "single-cell", "scRNA-seq", "single-nucleus",
                        "spatial transcriptomics", "cell atlas",
                        "cell type", "trajectory inference",
                    ],
                    "arxiv_categories": ["q-bio.GN", "q-bio.QM", "q-bio.CB"],
                    "priority": 3,
                },
                "Computational Biology & Methods": {
                    "keywords": [
                        "differential expression", "sequence alignment",
                        "bioinformatics pipeline", "benchmark",
                        "statistical model", "read mapping", "quality control",
                    ],
                    "arxiv_categories": ["q-bio.QM", "q-bio.GN"],
                    "priority": 3,
                },
            },
            "excluded_keywords": ["review", "workshop", "survey"],
        }


def calculate_date_windows(target_date: Optional[datetime] = None, days: int = 7) -> Tuple[datetime, datetime, datetime, datetime]:
    """
    Compute two date windows: a recent window (default 7 days) and the past year
    excluding that recent window.

    Args:
        target_date: Reference date; defaults to now if None.

    Returns:
        (window_30d_start, window_30d_end, window_1y_start, window_1y_end)
        - window_30d_start: Start of the recent window.
        - window_30d_end:   End of the recent window (= target_date).
        - window_1y_start:  Start of the past-year window.
        - window_1y_end:    End of the past-year window (= day before recent window).
    """
    if target_date is None:
        target_date = datetime.now()
    
    # Recent window: [target_date - days, target_date]
    window_30d_start = target_date - timedelta(days=days)
    window_30d_end = target_date

    # Past-year window (excluding the recent window)
    window_1y_start = target_date - timedelta(days=365)
    window_1y_end = target_date - timedelta(days=days + 1)
    
    return window_30d_start, window_30d_end, window_1y_start, window_1y_end


def search_arxiv_by_date_range(
    categories: List[str],
    start_date: datetime,
    end_date: datetime,
    max_results: int = 200,
    max_retries: int = 3
) -> List[Dict]:
    """
    Search arXiv for papers submitted within a given date range.

    Args:
        categories: List of arXiv category codes.
        start_date: Start of the date range.
        end_date:   End of the date range.
        max_results: Maximum number of results to fetch.
        max_retries: Maximum number of retry attempts.

    Returns:
        List of paper dicts.
    """
    # Build category query
    category_query = "+OR+".join([f"cat:{cat}" for cat in categories])

    # Build date-range query (arXiv uses YYYYMMDD format)
    date_query = f"submittedDate:[{start_date.strftime('%Y%m%d')}0000+TO+{end_date.strftime('%Y%m%d')}2359]"

    # Combine into a single query string
    full_query = f"({category_query})+AND+{date_query}"

    # Build the request URL
    url = (
        f"https://export.arxiv.org/api/query?"
        f"search_query={full_query}&"
        f"max_results={max_results}&"
        f"sortBy=submittedDate&"
        f"sortOrder=descending"
    )
    
    logger.info("[arXiv] Searching papers from %s to %s", start_date.date(), end_date.date())
    logger.debug("[arXiv] URL: %s...", url[:120])
    
    for attempt in range(max_retries):
        try:
            with urllib.request.urlopen(url, timeout=60) as response:
                xml_content = response.read().decode('utf-8')
                papers = parse_arxiv_xml(xml_content)
                logger.info("[arXiv] Found %d papers", len(papers))
                return papers
        except Exception as e:
            logger.warning("[arXiv] Error (attempt %d/%d): %s", attempt + 1, max_retries, e)
            if attempt < max_retries - 1:
                wait_time = (2 ** attempt) * 2
                logger.info("[arXiv] Retrying in %d seconds...", wait_time)
                time.sleep(wait_time)
            else:
                logger.error("[arXiv] Failed after %d attempts", max_retries)
                return []
    
    return []


def search_semantic_scholar_hot_papers(
    query: str,
    start_date: datetime,
    end_date: datetime,
    top_k: int = 20,
    max_retries: int = 3
) -> List[Dict]:
    """
    Search Semantic Scholar for high-impact papers within a given date range.

    Args:
        query:       Search query string.
        start_date:  Start of the date range.
        end_date:    End of the date range.
        top_k:       Return the top-K most influential papers.
        max_retries: Maximum number of retry attempts.

    Returns:
        List of paper dicts sorted by influential citation count (descending).
    """
    # Build date range string (Semantic Scholar uses YYYY-MM-DD:YYYY-MM-DD)
    date_range = f"{start_date.strftime('%Y-%m-%d')}:{end_date.strftime('%Y-%m-%d')}"

    # Build request parameters
    params = {
        "query": query,
        "publicationDateOrYear": date_range,
        "limit": 100,  # Fetch up to 100 most-relevant papers for local re-ranking
        "fields": SEMANTIC_SCHOLAR_FIELDS
    }
    
    headers = {
        "User-Agent": "StartMyWeek-PaperFetcher/1.0"
    }
    if S2_API_KEY:
        headers["x-api-key"] = S2_API_KEY
    
    logger.info("[S2] Searching hot papers from %s to %s", start_date.date(), end_date.date())
    logger.info("[S2] Query: '%s'", query)
    
    for attempt in range(max_retries):
        try:
            if HAS_REQUESTS:
                response = requests.get(
                    SEMANTIC_SCHOLAR_API_URL,
                    params=params,
                    headers=headers,
                    timeout=15
                )
                response.raise_for_status()
                data = response.json()
            else:
                # Fall back to urllib
                query_string = urllib.parse.urlencode(params)
                url = f"{SEMANTIC_SCHOLAR_API_URL}?{query_string}"
                req = urllib.request.Request(url, headers=headers)
                with urllib.request.urlopen(req, timeout=15) as response:
                    data = json.loads(response.read().decode('utf-8'))
            
            papers = data.get("data", [])
            if not papers:
                logger.info("[S2] No papers found")
                return []
            
            # Local secondary filtering and re-ranking
            valid_papers = []
            for p in papers:
                # Skip entries without a title or abstract
                if not p.get("title") or not p.get("abstract"):
                    continue

                # Guard against None values from the API
                inf_cit = p.get("influentialCitationCount") or 0
                cit = p.get("citationCount") or 0
                
                p["influentialCitationCount"] = inf_cit
                p["citationCount"] = cit
                
                # Tag source
                p["source"] = "semantic_scholar"
                p["hot_score"] = inf_cit  # Use influential citation count as the heat score

                # Populate stable `id` from externalIds so --skip-paper-ids works
                ext = p.get("externalIds") or {}
                if ext.get("PubMed"):
                    p["id"] = f"PMID:{ext['PubMed']}"
                elif ext.get("DOI"):
                    p["id"] = f"DOI:{ext['DOI']}"
                elif ext.get("CorpusId"):
                    p["id"] = f"S2:{ext['CorpusId']}"

                # Capture venue / journal name (for display + journal filter)
                venue = p.get("venue") or ""
                if not venue:
                    pv = p.get("publicationVenue") or {}
                    if isinstance(pv, dict):
                        venue = pv.get("name", "") or ""
                p["journal"] = venue

                # Extract affiliation information
                if p.get('authors') and not p.get('affiliations'):
                    affiliations = []
                    for a in p['authors']:
                        if not isinstance(a, dict):
                            continue
                        for affil in (a.get('affiliations') or []):
                            name = affil.get('name', '') if isinstance(affil, dict) else str(affil)
                            if name and name not in affiliations:
                                affiliations.append(name)
                    p['affiliations'] = affiliations

                # Normalise authors to list[str] BEFORE writing to the
                # output dict. Affiliations (extracted above) live
                # separately under p["affiliations"].
                p['authors'] = _normalize_authors(p.get('authors'))

                valid_papers.append(p)
            
            # Sort by influential citation count (descending)
            sorted_papers = sorted(
                valid_papers,
                key=lambda x: x["influentialCitationCount"],
                reverse=True
            )
            
            logger.info("[S2] Found %d valid papers, returning top %d", len(sorted_papers), top_k)
            return sorted_papers[:top_k]
            
        except Exception as e:
            error_msg = str(e)
            logger.warning("[S2] Error (attempt %d/%d): %s", attempt + 1, max_retries, e)
            
            # Check for a 429 Too Many Requests error
            is_rate_limit = False
            if HAS_REQUESTS and hasattr(e, 'response') and e.response is not None:
                is_rate_limit = e.response.status_code == 429
            else:
                is_rate_limit = "429" in error_msg or "Too Many Requests" in error_msg
            
            if attempt < max_retries - 1:
                # Use a longer back-off for 429 rate-limit errors
                if is_rate_limit:
                    wait_time = S2_RATE_LIMIT_WAIT
                    logger.warning("[S2] Rate limit hit. Waiting %d seconds...", wait_time)
                else:
                    wait_time = (2 ** attempt) * 2
                    logger.info("[S2] Retrying in %d seconds...", wait_time)
                time.sleep(wait_time)
            else:
                logger.error("[S2] Failed after %d attempts", max_retries)
                return []
    
    return []


def search_hot_papers_from_categories(
    categories: List[str],
    start_date: datetime,
    end_date: datetime,
    top_k_per_category: int = 5,
    config: Optional[Dict] = None
) -> List[Dict]:
    """
    Search for high-impact papers across multiple arXiv categories.

    Args:
        categories:         List of arXiv category codes.
        start_date:         Start of the date range.
        end_date:           End of the date range.
        top_k_per_category: Number of papers to return per category.
        config:             Research config used to extract user-defined keywords.

    Returns:
        Combined list of high-impact papers.
    """
    all_hot_papers = []
    seen_arxiv_ids = set()

    # Extract user-defined search keywords from the config (more precise than category terms)
    user_queries = []
    if config:
        domains = config.get('research_domains', {})
        for domain_name, domain_config in domains.items():
            keywords = domain_config.get('keywords', [])
            # Combine the first 3 keywords of each domain into a single query
            if keywords:
                query = ' '.join(keywords[:3])
                user_queries.append(query)

    # Fall back to category keywords if no user keywords are available
    if not user_queries:
        user_queries = [ARXIV_CATEGORY_KEYWORDS.get(cat, cat) for cat in categories]

    # Deduplicate queries
    seen_queries = set()
    unique_queries = []
    for q in user_queries:
        q_lower = q.lower()
        if q_lower not in seen_queries:
            seen_queries.add(q_lower)
            unique_queries.append(q)

    for query in unique_queries:
        
        papers = search_semantic_scholar_hot_papers(
            query=query,
            start_date=start_date,
            end_date=end_date,
            top_k=top_k_per_category
        )
        
        # Deduplicate by arXiv ID
        for p in papers:
            # Safely extract the ArXiv ID from the externalIds dict
            arxiv_id = p.get("externalIds", {}).get("ArXiv") if p.get("externalIds") else None

            # Write a unified arxiv_id field for the global dedup in Step 3
            p["arxiv_id"] = arxiv_id

            if arxiv_id and arxiv_id not in seen_arxiv_ids:
                seen_arxiv_ids.add(arxiv_id)
                all_hot_papers.append(p)
            elif not arxiv_id:
                # Keep papers without an arXiv ID (they may come from other sources)
                all_hot_papers.append(p)
        
        time.sleep(S2_CATEGORY_REQUEST_INTERVAL)
    
    # Final sort by influential citation count
    all_hot_papers.sort(key=lambda x: x.get("influentialCitationCount", 0), reverse=True)
    
    return all_hot_papers


def parse_arxiv_xml(xml_content: str) -> List[Dict]:
    """
    Parse an arXiv Atom XML response.

    Args:
        xml_content: Raw XML string returned by the arXiv API.

    Returns:
        List of paper dicts, each containing id, title, authors, abstract, etc.
    """
    papers = []
    
    try:
        root = ET.fromstring(xml_content)
        
        # Iterate over all <entry> elements
        for entry in root.findall('atom:entry', ARXIV_NS):
            paper = {}

            # Extract paper ID
            id_elem = entry.find('atom:id', ARXIV_NS)
            if id_elem is not None:
                paper['id'] = id_elem.text
                # Extract the bare arXiv ID from the URL
                match = re.search(r'arXiv:(\d+\.\d+)', paper['id'])
                if match:
                    paper['arxiv_id'] = match.group(1)
                else:
                    match = re.search(r'/(\d+\.\d+)$', paper['id'])
                    if match:
                        paper['arxiv_id'] = match.group(1)
            
            # Extract title
            title_elem = entry.find('atom:title', ARXIV_NS)
            if title_elem is not None:
                paper['title'] = title_elem.text.strip()

            # Extract abstract
            summary_elem = entry.find('atom:summary', ARXIV_NS)
            if summary_elem is not None:
                paper['summary'] = summary_elem.text.strip()

            # Extract authors (and optional affiliation)
            authors = []
            affiliations = []
            for author in entry.findall('atom:author', ARXIV_NS):
                name_elem = author.find('atom:name', ARXIV_NS)
                if name_elem is not None:
                    authors.append(name_elem.text)
                affil_elem = author.find('arxiv:affiliation', ARXIV_NS)
                if affil_elem is not None and affil_elem.text:
                    affil = affil_elem.text.strip()
                    if affil and affil not in affiliations:
                        affiliations.append(affil)
            paper['authors'] = authors
            paper['affiliations'] = affiliations  # may be an empty list

            # Extract publication date
            published_elem = entry.find('atom:published', ARXIV_NS)
            if published_elem is not None:
                paper['published'] = published_elem.text
                # Parse into a datetime object
                try:
                    paper['published_date'] = datetime.fromisoformat(
                        paper['published'].replace('Z', '+00:00')
                    )
                except (ValueError, TypeError):
                    paper['published_date'] = None
            
            # Extract last-updated date
            updated_elem = entry.find('atom:updated', ARXIV_NS)
            if updated_elem is not None:
                paper['updated'] = updated_elem.text

            # Extract categories
            categories = []
            for category in entry.findall('atom:category', ARXIV_NS):
                term = category.get('term')
                if term:
                    categories.append(term)
            paper['categories'] = categories
            
            # Extract PDF link
            for link in entry.findall('atom:link', ARXIV_NS):
                if link.get('title') == 'pdf':
                    paper['pdf_url'] = link.get('href')
                    break

            # Extract abstract page URL
            if 'id' in paper:
                paper['url'] = paper['id']

            # Tag source
            paper['source'] = 'arxiv'
            
            papers.append(paper)
            
    except ET.ParseError as e:
        logger.error("Error parsing XML: %s", e)
        raise
    
    return papers


# Scoring primitives (`calculate_relevance_score`, `calculate_recency_score`,
# `calculate_quality_score`, `calculate_recommendation_score`,
# `_resolve_reference_now`) were extracted to `scripts/_scoring.py` in
# 2026-05 per DEFERRED.md #5. They're imported at the top of this file
# and are still accessible as `search_arxiv.calculate_*_score` for
# backward compatibility with existing tests and call sites.


# Substrings that mark a research domain as biomedical (for bio_sources "auto").
_BIOMED_KEYWORD_MARKERS = (
    "biolog", "genom", "transcript", "rna", "dna", "protein", "gene", "cell",
    "clinical", "medical", "disease", "patient", "epigen", "chromatin",
    "methylation", "single-cell", "biomed", "neuro", "cancer", "immun",
    "microb", "drug", "molecul", "pathogen", "virus", "antibod",
)


def _bio_sources_enabled(config: Dict) -> bool:
    """Whether the biomedical sources (bioRxiv/medRxiv/PubMed) are searched.

    Explicit `bio_sources: true`/`false` always wins. Otherwise ("auto", or any
    unrecognised/absent value) the sources run ONLY when the config shows a
    biomedical signal — a `q-bio.*` arXiv category or a biomedical keyword. This
    fixes the QC finding that PubMed injected clinical-nutrition noise into a
    non-biomedical (humanitarian) persona, and that unknown values like
    "garbage" silently turned the sources on. A non-bio researcher who still
    wants PubMed can set `bio_sources: true`.
    """
    setting = config.get("bio_sources", "auto")
    if setting is True or setting == "true":
        return True
    if setting is False or setting == "false":
        return False
    for dom in (config.get("research_domains") or {}).values():
        for cat in (dom.get("arxiv_categories") or []):
            if str(cat).startswith("q-bio."):
                return True
        for kw in (dom.get("keywords") or []):
            kw_l = str(kw).lower()
            if any(marker in kw_l for marker in _BIOMED_KEYWORD_MARKERS):
                return True
    return False


# Broad cross-disciplinary arXiv categories, used only when neither --categories
# nor the config's research_domains supply any (keeps a bare run non-empty).
_FALLBACK_ARXIV_CATEGORIES = [
    "cs.AI", "cs.LG", "cs.CL", "cs.CV", "cs.NE", "stat.ML", "math.ST",
    "physics.comp-ph", "econ.GN", "q-bio.QM",
]


def _derive_arxiv_categories_from_config(config: Dict) -> List[str]:
    """Union of every domain's `arxiv_categories`, order-preserving and deduped.

    Makes the script field-agnostic on its own: previously this derivation lived
    only in SKILL.md's bash, so a direct (non-SKILL) invocation without
    --categories silently fell back to a CS-only default. Now `main()` calls this
    when --categories is absent.
    """
    cats: List[str] = []
    seen = set()
    for dom in (config.get("research_domains") or {}).values():
        for cat in (dom.get("arxiv_categories") or []):
            if cat not in seen:
                seen.add(cat)
                cats.append(cat)
    return cats


def _split_pool(unique_papers, pool_size, top_n):
    """Candidate pool for reranking + the keyword-only fallback list.

    `candidates` = top `pool_size` (>= top_n) papers, ranked. `top_papers` =
    first `top_n` of the pool — used directly when no rerank step runs.
    """
    size = max(pool_size, top_n)
    candidates = unique_papers[:size]
    return candidates, candidates[:top_n]


def _priority_weight(domains: Dict, domain_name: Optional[str]) -> float:
    """Per-domain `priority` (1–5) as a relevance multiplier for ranking.

    priority 3 is neutral (×1.0); 5 → ×1.67, 1 → ×0.33. This is the
    `priority: 1–5` the config has always documented ("weights the score") but
    never actually applied: it weights how a paper RANKS (its recommendation
    score), so a higher-priority topic's matches rise to the top. It does NOT
    change which papers clear the keyword-relevance gate.
    """
    if not domain_name:
        return 1.0
    raw = (domains.get(domain_name) or {}).get("priority", 3)
    try:
        p = float(raw)
    except (TypeError, ValueError):
        p = 3.0
    p = max(1.0, min(5.0, p))
    return p / 3.0


def _extra_source_enabled(spec: Dict, config: Dict) -> bool:
    """Decide whether an optional source (OpenAlex/Crossref/CORE) runs.

    Its config value may be a bool/"true"/"false", or a dict with an `enabled`
    key holding the same. "auto" (the default): keyless sources always run;
    keyed sources run only when their key_env resolves to a non-empty value.
    """
    raw = config.get(spec["cfg_key"], spec.get("default", "auto"))
    setting = raw.get("enabled", "auto") if isinstance(raw, dict) else raw
    if setting is True or setting == "true":
        return True
    if setting is False or setting == "false":
        return False
    if spec["key_env"] is None:
        return True  # keyless source — on by default under "auto"
    try:
        from _env_resolve import load_env_from_user_shell as _lenv
        _lenv((spec["key_env"],))
    except Exception:
        pass
    return bool(os.environ.get(spec["key_env"], "").strip())


def _resolve_scoring(config: Dict) -> Dict:
    """Merge the optional `scoring:` config block onto the tuned defaults.

    Exposes the otherwise-hardcoded scoring dials so a user can tune filtering
    and ranking from their YAML. Any bad value falls back to the default for
    that field. Returns: min_relevance, title_match, abstract_match,
    category_match, weights (normalized, ordinary-paper blend), and
    recency_thresholds (None → use the built-in buckets).
    """
    sc = config.get('scoring') or {}
    if not isinstance(sc, dict):
        sc = {}

    def _num(key, default):
        try:
            return float(sc[key])
        except (KeyError, TypeError, ValueError):
            return default

    # Ranking weights: merge any provided keys onto WEIGHTS_NORMAL, then
    # normalize to sum 1.0 so a partial or off-scale override keeps the 0–10
    # ceiling intact.
    weights = dict(WEIGHTS_NORMAL)
    user_w = sc.get('weights')
    if isinstance(user_w, dict):
        for k in weights:
            try:
                weights[k] = float(user_w[k])
            except (KeyError, TypeError, ValueError):
                pass
    total = sum(weights.values())
    weights = {k: v / total for k, v in weights.items()} if total > 0 else dict(WEIGHTS_NORMAL)

    # Recency buckets: a list of [days, score] pairs, sorted ascending by days.
    thresholds = None
    raw_th = sc.get('recency_thresholds')
    if isinstance(raw_th, list):
        parsed = []
        for item in raw_th:
            try:
                days, score = item
                parsed.append((int(days), float(score)))
            except (TypeError, ValueError):
                continue
        if parsed:
            thresholds = sorted(parsed, key=lambda x: x[0])

    return {
        'min_relevance': _num('min_relevance', MIN_KEYWORD_ONLY_RELEVANCE),
        'min_keyword_matches': max(1, int(_num('min_keyword_matches', 1))),
        'title_match': _num('title_match', RELEVANCE_TITLE_KEYWORD_BOOST),
        'abstract_match': _num('abstract_match', RELEVANCE_SUMMARY_KEYWORD_BOOST),
        'category_match': _num('category_match', RELEVANCE_CATEGORY_MATCH_BOOST),
        'weights': weights,
        'recency_thresholds': thresholds,
    }


def filter_and_score_papers(
    papers: List[Dict],
    config: Dict,
    target_date: Optional[datetime] = None,
    is_hot_paper_batch: bool = False
) -> List[Dict]:
    """
    Filter and score a list of papers.

    Args:
        papers:             List of paper dicts.
        config:             Research configuration.
        target_date:        Reference date for recency scoring.
        is_hot_paper_batch: True when scoring the high-impact (Semantic Scholar) batch.

    Returns:
        Filtered and scored paper list, sorted by recommendation score (descending).
    """
    domains = config.get('research_domains', {})
    excluded_keywords = config.get('excluded_keywords', [])
    sc = _resolve_scoring(config)  # effective scoring dials (config-overridable)

    scored_papers = []

    for paper in papers:
        # Normalize published_date: bio sources store it as "YYYY-MM-DD" string;
        # convert to datetime so all downstream scoring functions work uniformly
        if 'published_date' in paper and isinstance(paper['published_date'], str):
            try:
                paper['published_date'] = datetime.strptime(paper['published_date'], '%Y-%m-%d')
            except (ValueError, TypeError):
                paper['published_date'] = None

        # Compute relevance
        relevance, matched_domain, matched_keywords = calculate_relevance_score(
            paper, domains, excluded_keywords,
            title_boost=sc['title_match'],
            summary_boost=sc['abstract_match'],
            category_boost=sc['category_match'],
        )

        # Scoring is source-neutral: a paper is ranked by how well it matches
        # the user's keywords, not by which site it came from. (No per-source
        # boosts — the source a paper arrives from must not tilt its rank.)

        # Skip papers with zero relevance
        if relevance == 0:
            continue

        # Require that keyword-only relevance (excluding broad arXiv category matches)
        # is sufficient — prevents papers that matched only a category + 1 incidental
        # abstract word from being included.
        n_cat_matches = sum(1 for kw in matched_keywords if ARXIV_CATEGORY_PATTERN.match(kw))
        keyword_only_score = relevance - n_cat_matches * sc['category_match']
        if keyword_only_score < sc['min_relevance']:
            continue

        # Topical-signal gate (QC precision fix): one bare ambiguous word
        # ("alignment", "simulation", "localization") false-matches across fields.
        # Require EITHER >=min_keyword_matches distinct keyword hits, OR >=1 compound
        # keyword (a space/hyphen/&// term like "transposable element", "single-cell",
        # "ATAC-seq"), which is specific enough to stand alone.
        kw_matches = [kw for kw in matched_keywords if not ARXIV_CATEGORY_PATTERN.match(kw)]
        has_compound = any(any(c in kw for c in (' ', '-', '&', '/')) for kw in kw_matches)
        if len(kw_matches) < sc['min_keyword_matches'] and not has_compound:
            continue

        # Compute recency
        if 'published_date' in paper:
            recency = calculate_recency_score(paper.get('published_date'), target_date,
                                              thresholds=sc['recency_thresholds'])
        else:
            # For Semantic Scholar papers, fall back to the publicationDate field
            pub_date_str = paper.get('publicationDate')
            if pub_date_str:
                pub_date = None
                for fmt in ('%Y-%m-%d', '%Y-%m', '%Y'):
                    try:
                        pub_date = datetime.strptime(pub_date_str, fmt)
                        break
                    except (ValueError, TypeError):
                        continue
                recency = calculate_recency_score(
                    pub_date, target_date, thresholds=sc['recency_thresholds']) if pub_date else 0
            else:
                recency = 0

        # Compute popularity
        if is_hot_paper_batch:
            # High-impact batch: derive popularity from influentialCitationCount
            inf_cit = paper.get('influentialCitationCount', 0)
            popularity = min(
                inf_cit / (POPULARITY_INFLUENTIAL_CITATION_FULL_SCORE / SCORE_MAX),
                SCORE_MAX,
            )
        else:
            # Ordinary papers (no citation data): estimate popularity from recency.
            # Very fresh papers may have high potential impact even before citations accrue.
            if 'published_date' in paper and paper['published_date']:
                pub = paper['published_date']
                now = _resolve_reference_now(pub, target_date)
                days_old = (now - pub).days
                if days_old <= 7:
                    popularity = 2.0  # Very new — high potential
                elif days_old <= 14:
                    popularity = 1.5
                elif days_old <= 30:
                    popularity = 1.0
                else:
                    popularity = 0.5
            else:
                popularity = 0.5  # Conservative default when date is unknown

        # Compute quality
        summary = paper.get('summary', '') if 'summary' in paper else paper.get('abstract', '')
        quality = calculate_quality_score(summary)

        # Compute combined recommendation score. Per-domain `priority` weights
        # how a paper RANKS (not whether it passed the gate above): a higher-
        # priority topic's matches get a higher recommendation score.
        weighted_relevance = relevance * _priority_weight(domains, matched_domain)
        recommendation_score = calculate_recommendation_score(
            weighted_relevance, recency, popularity, quality, is_hot_paper_batch,
            # User weights tune the ordinary-paper blend; the high-citation
            # ("hot") batch keeps its popularity-weighted blend.
            weights=None if is_hot_paper_batch else sc['weights'],
        )

        # Attach scoring info to the paper dict
        paper['scores'] = {
            'relevance': round(relevance, 2),
            'recency': round(recency, 2),
            'popularity': round(popularity, 2),
            'quality': round(quality, 2),
            'recommendation': recommendation_score
        }
        paper['matched_domain'] = matched_domain
        paper['matched_keywords'] = matched_keywords
        paper['is_hot_paper'] = is_hot_paper_batch

        scored_papers.append(paper)

    # Sort by recommendation score (descending)
    scored_papers.sort(key=lambda x: x['scores']['recommendation'], reverse=True)

    return scored_papers


def main():
    """Entry point."""
    import argparse

    # Use shared resolver: $OBSIDIAN_VAULT_PATH/... → ~/.config/paperadar/config.yaml
    try:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        from _config_paths import resolve_config_path
        default_config = resolve_config_path(None)
    except ImportError:
        default_config = os.environ.get('OBSIDIAN_VAULT_PATH', '')
        if default_config:
            default_config = os.path.join(default_config, '99_System', 'Config', 'research_interests.yaml')

    parser = argparse.ArgumentParser(description='Search and filter arXiv papers with Semantic Scholar integration')
    parser.add_argument('--config', type=str,
                        default=default_config or None,
                        help='Path to research interests config file (defaults to ~/.config/paperadar/config.yaml or $OBSIDIAN_VAULT_PATH/99_System/Config/research_interests.yaml)')
    parser.add_argument('--output', type=str, default='arxiv_filtered.json',
                        help='Output JSON file path')
    parser.add_argument('--max-results', type=int, default=200,
                        help='Maximum number of results to fetch from arXiv')
    parser.add_argument('--top-n', type=int, default=10,
                        help='Number of top papers to return')
    parser.add_argument('--pool-size', type=int, default=25,
                        help='Candidate pool size emitted for the rerank step '
                             '(>= top-n). Default 25.')
    parser.add_argument('--target-date', type=str, default=None,
                        help='Target date (YYYY-MM-DD) for filtering')
    parser.add_argument('--categories', type=str, default=None,
                        help='Comma-separated arXiv categories. If omitted, derived '
                             'from the config research_domains (union), then a broad '
                             'cross-disciplinary fallback.')
    parser.add_argument('--skip-hot-papers', action='store_true',
                        help='Skip searching hot papers from Semantic Scholar')
    parser.add_argument('--days', type=int, default=7,
                        help='Number of days to search for recent papers (default: 7)')

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s [%(levelname)s] %(message)s',
        datefmt='%H:%M:%S',
        stream=sys.stderr,
    )

    if not args.config:
        logger.error("No config file path specified. Use --config or set the OBSIDIAN_VAULT_PATH environment variable.")
        return 1

    logger.info("Loading config from: %s", args.config)
    config = load_research_config(args.config)

    # Parse the target date
    target_date = None
    if args.target_date:
        try:
            target_date = datetime.strptime(args.target_date, '%Y-%m-%d')
            logger.info("Target date: %s", args.target_date)
        except ValueError:
            logger.error("Invalid target date format: %s", args.target_date)
            return 1
    else:
        target_date = datetime.now()
        logger.info("Using current date: %s", target_date.strftime('%Y-%m-%d'))

    window_30d_start, window_30d_end, window_1y_start, window_1y_end = calculate_date_windows(target_date, days=args.days)
    logger.info("Date windows:")
    logger.info("  Recent %d days: %s to %s", args.days, window_30d_start.date(), window_30d_end.date())
    logger.info("  Past year (before recent window): %s to %s", window_1y_start.date(), window_1y_end.date())

    # Parse categories: explicit --categories wins; else derive from the config's
    # research_domains (field-agnostic, no longer SKILL.md-only); else broad fallback.
    if args.categories:
        categories = [c.strip() for c in args.categories.split(',') if c.strip()]
    else:
        categories = _derive_arxiv_categories_from_config(config)
        if not categories:
            categories = list(_FALLBACK_ARXIV_CATEGORIES)
        logger.info("Derived arXiv categories from config: %s", ",".join(categories))

    all_scored_papers = []
    recent_papers = []
    hot_papers = []

    # ========== Step 1: Search recent papers from arXiv ==========
    logger.info("=" * 70)
    logger.info("Step 1: Searching recent papers (last %d days) from arXiv", args.days)
    logger.info("=" * 70)
    
    recent_papers = search_arxiv_by_date_range(
        categories=categories,
        start_date=window_30d_start,
        end_date=window_30d_end,
        max_results=args.max_results
    )
    
    if recent_papers:
        scored_recent = filter_and_score_papers(
            papers=recent_papers,
            config=config,
            target_date=target_date,
            is_hot_paper_batch=False
        )
        logger.info("Scored %d recent papers", len(scored_recent))
        all_scored_papers.extend(scored_recent)
    else:
        logger.warning("No recent papers found")

    # ========== Step 2: Search high-impact papers from Semantic Scholar (past year) ==========
    if not args.skip_hot_papers:
        logger.info("=" * 70)
        logger.info("Step 2: Searching hot papers (past year) from Semantic Scholar")
        logger.info("=" * 70)
        
        hot_papers = search_hot_papers_from_categories(
            categories=categories,
            start_date=window_1y_start,
            end_date=window_1y_end,
            top_k_per_category=5,
            config=config
        )

        # Top-tier journal filter (Semantic Scholar): keep only papers whose
        # venue matches one of the configured prioritize_journals.
        # Empty/missing list = no filtering.
        prioritized = [j.lower() for j in (config.get("prioritize_journals") or [])]
        if prioritized and hot_papers:
            before = len(hot_papers)
            hot_papers = [
                p for p in hot_papers
                if any(j in (p.get("journal", "") or "").lower() for j in prioritized)
            ]
            logger.info("[S2 journal filter] %d → %d papers after journal whitelist",
                        before, len(hot_papers))

        if hot_papers:
            scored_hot = filter_and_score_papers(
                papers=hot_papers,
                config=config,
                target_date=target_date,
                is_hot_paper_batch=True
            )
            logger.info("Scored %d hot papers", len(scored_hot))
            all_scored_papers.extend(scored_hot)
        else:
            logger.warning("No hot papers found from Semantic Scholar")
    else:
        logger.info("Skipping hot paper search (disabled by user)")

    # ========== Step 2.5: Bio sources (bioRxiv, medRxiv, PubMed) ==========
    # `bio_status` is propagated to the output JSON so the SKILL.md Step 2
    # guard can warn the user when this section produced an incomplete
    # picture (per "sanity checks must fail loud" discipline).
    bio_papers = []
    bio_status = BIO_SOURCES_STATUS  # "ok" if import succeeded
    bio_enabled = _bio_sources_enabled(config)
    if HAS_BIO_SOURCES and bio_enabled:
        logger.info("=" * 70)
        logger.info("Step 2.5: Searching bioRxiv, medRxiv, and PubMed")
        logger.info("=" * 70)

        # Each source is wrapped so a single API failure (timeout / 5xx /
        # network) doesn't silently zero the contribution. The first
        # source that errors flips bio_status to "api_error:<source>:<msg>".
        try:
            biorxiv_papers = search_biorxiv(
                config, days=args.days, server="biorxiv",
                target_date=target_date,
            )
            logger.info("[bioRxiv] Found %d matching preprints",
                        len(biorxiv_papers))
        except Exception as e:
            biorxiv_papers = []
            bio_status = f"api_error:biorxiv:{e}"
            logger.error("[bioRxiv] failed: %s", e)

        try:
            medrxiv_papers = search_biorxiv(
                config, days=args.days, server="medrxiv",
                target_date=target_date,
            )
            logger.info("[medRxiv] Found %d matching preprints",
                        len(medrxiv_papers))
        except Exception as e:
            medrxiv_papers = []
            if bio_status == "ok":
                bio_status = f"api_error:medrxiv:{e}"
            logger.error("[medRxiv] failed: %s", e)

        try:
            pubmed_papers = search_pubmed(
                config, days=args.days, target_date=target_date)
            logger.info("[PubMed] Found %d papers", len(pubmed_papers))
        except Exception as e:
            pubmed_papers = []
            if bio_status == "ok":
                bio_status = f"api_error:pubmed:{e}"
            logger.error("[PubMed] failed: %s", e)

        bio_papers = biorxiv_papers + medrxiv_papers + pubmed_papers
        if bio_papers:
            scored_bio = filter_and_score_papers(
                papers=bio_papers,
                config=config,
                target_date=target_date,
                is_hot_paper_batch=False
            )
            logger.info("Scored %d bio-source papers", len(scored_bio))
            all_scored_papers.extend(scored_bio)
    elif not bio_enabled:
        bio_status = "disabled"
        logger.info("Bio sources turned off (bio_sources: false) "
                    "— skipping bioRxiv/medRxiv/PubMed")
    else:
        logger.info("Bio sources not available — install search_pubmed.py "
                    "and search_biorxiv.py to enable")

    # ========== Step 2.6: Extra cross-disciplinary sources ==========
    # OpenAlex, Crossref, CORE — each gated by config + key availability via
    # the _EXTRA_SOURCES registry. A source that errors mid-run drops to [] and
    # records its status; the rest of the pipeline is unaffected.
    extra_counts = {}
    extra_status = {}
    for spec in _EXTRA_SOURCES:
        name = spec["name"]
        if not _extra_source_enabled(spec, config):
            extra_counts[name] = 0
            extra_status[name] = "disabled"
            logger.info("%s disabled for this config — skipping", name)
            continue
        logger.info("=" * 70)
        logger.info("Step 2.6: Searching %s (cross-disciplinary)", name)
        logger.info("=" * 70)
        try:
            papers = spec["fn"](config, days=args.days, target_date=target_date)
            extra_counts[name] = len(papers)
            extra_status[name] = "ok"
            logger.info("[%s] Found %d papers", name, len(papers))
        except Exception as e:
            papers = []
            extra_counts[name] = 0
            extra_status[name] = f"api_error:{e}"
            logger.error("[%s] failed: %s", name, e)
        if papers:
            scored_extra = filter_and_score_papers(
                papers=papers,
                config=config,
                target_date=target_date,
                is_hot_paper_batch=False
            )
            logger.info("Scored %d %s papers", len(scored_extra), name)
            all_scored_papers.extend(scored_extra)

    # ========== Step 3: Merge and rank results ==========
    logger.info("=" * 70)
    logger.info("Step 3: Merging and ranking results")
    logger.info("=" * 70)

    # Sort by recommendation score (descending)
    all_scored_papers.sort(key=lambda x: x['scores']['recommendation'], reverse=True)

    # Deduplicate: prefer arXiv ID match; fall back to normalized title
    # Cross-source dedup: a work can arrive as an arXiv preprint (has
    # arxiv_id) AND from PubMed/bioRxiv (no arxiv_id, same title). We must
    # register the normalized title for EVERY paper — not only the
    # arxiv-id-less ones — or the second copy slips through.
    seen_ids = set()
    seen_titles = set()
    unique_papers = []
    for p in all_scored_papers:
        arxiv_id = p.get('arxiv_id') or p.get('arxivId')
        title = p.get('title', '')
        title_normalized = re.sub(r'[^a-z0-9\s]', '', title.lower()).strip()
        if arxiv_id and arxiv_id in seen_ids:
            continue
        if title_normalized and title_normalized in seen_titles:
            continue
        if arxiv_id:
            seen_ids.add(arxiv_id)
        if title_normalized:
            seen_titles.add(title_normalized)
        unique_papers.append(p)
    
    logger.info("Total unique papers after deduplication: %d", len(unique_papers))

    if len(unique_papers) == 0:
        logger.warning("No papers matched the criteria!")
        return 1

    # Candidate pool (for the rerank step) + keyword-only fallback top-N.
    candidates, top_papers = _split_pool(unique_papers, args.pool_size, args.top_n)

    # Add note_filename to every candidate (the rerank step may promote any of
    # them into top_papers), matching generate_note.py's naming rules.
    for paper in candidates:
        paper['note_filename'] = title_to_note_filename(paper.get('title', ''))

    # Assemble output dict
    output = {
        'target_date': args.target_date or target_date.strftime('%Y-%m-%d'),
        'date_windows': {
            'recent_30d': {
                'start': window_30d_start.strftime('%Y-%m-%d'),
                'end': window_30d_end.strftime('%Y-%m-%d')
            },
            'past_year': {
                'start': window_1y_start.strftime('%Y-%m-%d'),
                'end': window_1y_end.strftime('%Y-%m-%d')
            }
        },
        'total_recent': len(recent_papers),
        'total_hot': len(hot_papers),
        'total_bio': len(bio_papers),
        'bio_status': bio_status,  # "ok" | "disabled" | "import_failed:..." | "api_error:..."
        # Per-source results for the optional cross-disciplinary sources, e.g.
        # {"OpenAlex": {"count": 12, "status": "ok"}, "Crossref": {...}, ...}
        'extra_sources': {
            name: {'count': extra_counts.get(name, 0),
                   'status': extra_status.get(name, 'disabled')}
            for name in (s['name'] for s in _EXTRA_SOURCES)
        },
        'total_unique': len(unique_papers),
        'candidates': candidates,
        'top_papers': top_papers
    }

    # Save results — atomic write so concurrent /paperadar runs (or
    # cron-driven re-runs that overlap) cannot corrupt the file
    # mid-write. See `scripts/_atomic.py` for the temp-then-rename
    # rationale and `~/.claude/sessions/2026-05-19-pipeline-overhaul/
    # DEFERRED.md` item #4 for the original race report.
    try:
        from _atomic import atomic_write_json
    except ImportError:
        _here = os.path.dirname(os.path.abspath(__file__))
        if _here not in sys.path:
            sys.path.insert(0, _here)
        from _atomic import atomic_write_json
    atomic_write_json(output, args.output)

    logger.info("Results saved to: %s", args.output)
    logger.info("Top %d papers:", len(top_papers))
    for i, p in enumerate(top_papers, 1):
        hot_marker = " [HOT]" if p.get('is_hot_paper') else ""
        logger.info("  %d. %s... (Score: %s)%s", i, p.get('title', 'N/A')[:60], p['scores']['recommendation'], hot_marker)

    # Also write to stdout for pipeline consumption
    print(json.dumps(output, ensure_ascii=False, indent=2, default=str))

    return 0


if __name__ == '__main__':
    sys.exit(main())
